# Generated by Django 4.1.4 on 2022-12-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='photo',
            field=models.ImageField(default='images/user.png', upload_to='profile/image/'),
        ),
    ]
