# Generated by Django 4.1.4 on 2022-12-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, default='default/product.png', null=True, upload_to='product/images'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
